### ISSUE TITLE
webgl实现ps混合模式第一章~正片叠底、滤色 | 会飞的猪的个人博客

### ISSUE THREAD

**Issue by dearDreamWeb** [dearDreamWeb/personal-blog#9]
https://blogwxb.cn/webgl%E5%AE%9E%E7%8E%B0ps%E6%B7%B7%E5%90%88%E6%A8%A1%E5%BC%8F%E7%AC%AC%E4%B8%80%E7%AB%A0-%E6%AD%A3%E7%89%87%E5%8F%A0%E5%BA%95%E3%80%81%E6%BB%A4%E8%89%B2/ 

 主要是分享自己在Web前端的一些入的坑，脱的坑的经历，也会是分享一些Node后端的知识。

**Comment by wtianye** [comment]
如果有很多张图片，该怎么混合呢？

**Comment by dearDreamWeb** [comment]
叠加计算，算完第一张和第二张的叠加之后，让第一张和第二张结果再和第三张的叠加。不知道这会不会是你想要的结果

**Comment by dearDreamWeb** [comment]
> 如果有很多张图片，该怎么混合呢？

叠加计算，算完第一张和第二张的叠加之后，让第一张和第二张结果再和第三张的叠加。不知道这会不会是你想要的结果

**Comment by wtianye** [comment]
第一张和第二张的结果绘制到canvas上，然后从canvas获取图片像素，再和第三张叠加吗？感觉这样效率有点低。可以使用帧缓存吗

**Comment by dearDreamWeb** [comment]
> 第一张和第二张的结果绘制到canvas上，然后从canvas获取图片像素，再和第三张叠加吗？感觉这样效率有点低。可以使用帧缓存吗
你可以使用帧缓存试试，我之前没有接触过你说的这种需求

**Comment by wtianye** [comment]
好的，我试试，感谢博主的解答
